const comSigs = require('./com-signals.js')

const test1 = comSigs.getDataStreamBuffer('bvwbjplbgvbhsrlpgdmjqwftvncz', 4)
const test2 = comSigs.getDataStreamBuffer('nppdvjthqldpwncqszvftbrmjlhg', 4)
const test3 = comSigs.getDataStreamBuffer('nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg', 4)
const test4 = comSigs.getDataStreamBuffer('zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw', 4)

const test5 = comSigs.getDataStreamBuffer('mjqjpqmgbljsphdztnvjfqwrcgsmlb', 14)
const test6 = comSigs.getDataStreamBuffer('bvwbjplbgvbhsrlpgdmjqwftvncz', 14)
const test7 = comSigs.getDataStreamBuffer('nppdvjthqldpwncqszvftbrmjlhg', 14)
const test8 = comSigs.getDataStreamBuffer('nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg', 14)
const test9 = comSigs.getDataStreamBuffer('zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw', 14)

console.assert(test1 === 5, 'Test 1 5:' + test1)
console.assert(test2 === 6, 'Test 2 6:' + test2)
console.assert(test3 === 10, 'Test 3 10:' + test3)
console.assert(test4 === 11, 'Test 4 11:' + test4)
console.assert(test5 === 19, 'Test 5 19:' + test5)
console.assert(test6 === 23, 'Test 6 23:' + test6)
console.assert(test7 === 23, 'Test 7 23:' + test7)
console.assert(test8 === 29, 'Test 8 29:' + test8)
console.assert(test9 === 26, 'Test 9 26:' + test9)
